baseURL: "https://fpvhub.ch"
title: "FPV Hub"
defaultContentLanguage: de
disableKinds: ["taxonomy", "term", "RSS"]
mediaTypes:
  model/stl:
    suffixes: ["stl"]
  model/3mf:
    suffixes: ["3mf"]

module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: content
      target: static
      includeFiles: "**/*.stl,**/*.3mf"
